CREATE DATABASE IF NOT EXISTS reach17;
USE reach17;

CREATE TABLE IF NOT EXISTS tipologie (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS corsi (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(255) NOT NULL UNIQUE,
  id_tipologia INT NOT NULL,
  FOREIGN KEY (id_tipologia) REFERENCES tipologie(id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS atenei (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(255) NOT NULL UNIQUE
);





CREATE TABLE IF NOT EXISTS associazioni (
  id INT AUTO_INCREMENT PRIMARY KEY,
  id_corso INT NOT NULL,
  id_ateneo INT NOT NULL,
  UNIQUE (id_corso, id_ateneo),
  FOREIGN KEY (id_corso) REFERENCES corsi(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY (id_ateneo) REFERENCES atenei(id) ON DELETE RESTRICT ON UPDATE CASCADE
);
